export const mockRiskApp = [
  {
    id: "APP-001",
    client: "Codreanu Matei Sergiu",
    score: 420,
    status: "rejected",
    reasonCodes: ["INC_INCOME", "MISSING_DOC"],
    kyc: {
      idFront: "/mocks/id-front.jpg",
      idBack: "/mocks/id-back.jpg",
      selfie: "/mocks/selfie.jpg",
      status: "unclear",
    },
    creditAmount: 10000,
    income: {
      amount: 3500,
      employer: "SC Ex SRL",
      contractType: "Full-time",
      history: ["2024-01", "2023-12"],
    },
    documents: [
      { name: "CI.pdf", url: "#", uploadedAt: "2024-09-01" },
      { name: "FisaVenit.pdf", url: "#", uploadedAt: "2024-09-02" },
    ],
    notes: [
      { text: "Client cu venituri fluctuante", time: "2024-11-01 10:00" },
    ],
    requestedDocuments: [],
  },
  {
    id: "APP-002",
    client: "Ionescu Marian Andra",
    score: 760,
    status: "approved",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 20000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
  {
    id: "APP-003",
    client: "Popescu Alexandru",
    score: 420,
    status: "manual_review",
    reasonCodes: ["INC_INCOME", "MISSING_DOC"],
    kyc: {
      idFront: "/mocks/id-front.jpg",
      idBack: "/mocks/id-back.jpg",
      selfie: "/mocks/selfie.jpg",
      status: "unclear",
    },
    creditAmount: 10000,
    income: {
      amount: 3500,
      employer: "SC Ex SRL",
      contractType: "Full-time",
      history: ["2024-01", "2023-12"],
    },
    documents: [
      { name: "CI.pdf", url: "#", uploadedAt: "2024-09-01" },
      { name: "FisaVenit.pdf", url: "#", uploadedAt: "2024-09-02" },
    ],
    notes: [
      { text: "Client cu venituri fluctuante", time: "2024-11-01 10:00" },
    ],
    requestedDocuments: [],
  },
  {
    id: "APP-004",
    client: "Maria Ionescu",
    score: 760,
    status: "pending",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 30000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
  {
    id: "APP-005",
    client: "Ion Popescu",
    score: 420,
    status: "manual_review",
    reasonCodes: ["INC_INCOME", "MISSING_DOC"],
    kyc: {
      idFront: "/mocks/id-front.jpg",
      idBack: "/mocks/id-back.jpg",
      selfie: "/mocks/selfie.jpg",
      status: "unclear",
    },
    creditAmount: 10000,
    income: {
      amount: 3500,
      employer: "SC Ex SRL",
      contractType: "Full-time",
      history: ["2024-01", "2023-12"],
    },
    documents: [
      { name: "CI.pdf", url: "#", uploadedAt: "2024-09-01" },
      { name: "FisaVenit.pdf", url: "#", uploadedAt: "2024-09-02" },
    ],
    notes: [
      { text: "Client cu venituri fluctuante", time: "2024-11-01 10:00" },
    ],
    requestedDocuments: [],
  },
  {
    id: "APP-006",
    client: "Maria Ionescu",
    score: 760,
    status: "pending",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 5000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
  {
    id: "APP-007",
    client: "Ion Popescu",
    score: 420,
    status: "manual_review",
    reasonCodes: ["INC_INCOME", "MISSING_DOC"],
    kyc: {
      idFront: "/mocks/id-front.jpg",
      idBack: "/mocks/id-back.jpg",
      selfie: "/mocks/selfie.jpg",
      status: "unclear",
    },
    creditAmount: 2000,
    income: {
      amount: 3500,
      employer: "SC Ex SRL",
      contractType: "Full-time",
      history: ["2024-01", "2023-12"],
    },
    documents: [
      { name: "CI.pdf", url: "#", uploadedAt: "2024-09-01" },
      { name: "FisaVenit.pdf", url: "#", uploadedAt: "2024-09-02" },
    ],
    notes: [
      { text: "Client cu venituri fluctuante", time: "2024-11-01 10:00" },
    ],
    requestedDocuments: [],
  },
  {
    id: "APP-008",
    client: "Maria Ionescu",
    score: 760,
    status: "pending",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 10000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
  {
    id: "APP-009",
    client: "Maria Ionescu",
    score: 760,
    status: "pending",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 25000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
  {
    id: "APP-010",
    client: "Ion Popescu",
    score: 420,
    status: "manual_review",
    reasonCodes: ["INC_INCOME", "MISSING_DOC"],
    kyc: {
      idFront: "/mocks/id-front.jpg",
      idBack: "/mocks/id-back.jpg",
      selfie: "/mocks/selfie.jpg",
      status: "unclear",
    },
    creditAmount: 10000,
    income: {
      amount: 3500,
      employer: "SC Ex SRL",
      contractType: "Full-time",
      history: ["2024-01", "2023-12"],
    },
    documents: [
      { name: "CI.pdf", url: "#", uploadedAt: "2024-09-01" },
      { name: "FisaVenit.pdf", url: "#", uploadedAt: "2024-09-02" },
    ],
    notes: [
      { text: "Client cu venituri fluctuante", time: "2024-11-01 10:00" },
    ],
    requestedDocuments: [],
  },
  {
    id: "APP-011",
    client: "Maria Ionescu",
    score: 760,
    status: "pending",
    reasonCodes: [],
    kyc: {
      idFront: "/mocks/id-front-2.jpg",
      idBack: "/mocks/id-back-2.jpg",
      selfie: "/mocks/selfie-2.jpg",
      status: "verified",
    },
    creditAmount: 44000,
    income: {
      amount: 6200,
      employer: "Firma SRL",
      contractType: "Full-time",
      history: ["2024-10", "2024-09"],
    },
    documents: [{ name: "CI.pdf", url: "#", uploadedAt: "2024-10-01" }],
    notes: [],
    requestedDocuments: [],
  },
];
